name: Chat nessaging app CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
      uses: actions/checkout@v2
   

